swagger: '2.0'
info:
  title: G-Authy API
  version: '1.0'
paths:
  /users:
    get:
      tags:
        - users
      summary: Get all users
      responses:
        '200':
          description: A list of users
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
    post:
      tags:
        - users
      summary: Create a new user
      parameters:
        - in: body
          name: user
          schema:
            $ref: '#/definitions/User'
      responses:
        '201':
          description: User created
  /users/{id}:
    get:
      tags:
        - users
      summary: Get a user by ID
      parameters:
        - in: path
          name: id
          required: true
          type: string
      responses:
        '200':
          description: A single user
          schema:
            $ref: '#/definitions/User'
    put:
      tags:
        - users
      summary: Update a user by ID
      parameters:
        - in: path
          name: id
          required: true
          type: string
        - in: body
          name: user
          schema:
            $ref: '#/definitions/User'
      responses:
        '200':
          description: User updated
    delete:
      tags:
        - users
      summary: Delete a user by ID
      parameters:
        - in: path
          name: id
          required: true
          type: string
      responses:
        '204':
          description: User deleted
  /users/{id}/vaults/{vault_id}:
    get:
      tags:
        - Users
        - Vaults
      summary: Get a specific vault within a user
      responses:
        '200':
          description: A vault object
    put:
      tags:
        - Users
        - Vaults
      summary: Update a specific vault within a user
      responses:
        '200':
          description: Vault updated
    delete:
      tags:
        - Users
        - Vaults
      summary: Delete a specific vault within a user
      responses:
        '204':
          description: Vault deleted
  /users/{id}/secrets/{secret_id}:
    get:
      tags:
        - Users
        - Secrets
      summary: Get a specific secret within a user
      responses:
        '200':
          description: A secret object
    put:
      tags:
        - Users
        - Secrets
      summary: Update a specific secret within a user
      responses:
        '200':
          description: Secret updated
    delete:
      tags:
        - Users
        - Secrets
      summary: Delete a specific secret within a user
      responses:
        '204':
          description: Secret deleted
 
  /tenants:
    get:
      tags:
        - tenants
      summary: Get all tenants
      responses:
        '200':
          description: A list of tenants
          schema:
            type: array
            items:
              $ref: '#/definitions/Tenant'
    post:
      tags:
        - tenants
      summary: Create a new tenant
      parameters:
        - in: body
          name: tenant
          schema:
            $ref: '#/definitions/Tenant'
      responses:
        '201':
          description: Tenant created
  /tenants/{id}:
    get:
      tags:
        - tenants
      summary: Get a tenant by ID
      parameters:
        - in: path
          name: id
          required: true
          type: string
      responses:
        '200':
          description: A single tenant
          schema:
            $ref: '#/definitions/Tenant'
    put:
      tags:
        - tenants
      summary: Update a tenant by ID
      parameters:
        - in: path
          name: id
          required: true
          type: string
        - in: body
          name: tenant
          schema:
            $ref: '#/definitions/Tenant'
      responses:
        '200':
          description: Tenant updated
    delete:
      tags:
        - tenants
      summary: Delete a tenant by ID
      parameters:
        - in: path
          name: id
          required: true
          type: string
      responses:
        '204':
          description: Tenant deleted
  /tenants/{id}/users/{user_id}:
    get:
      tags:
        - Tenants
        - Users
      summary: Get a specific user within a tenant
      responses:
        '200':
          description: A user object
    put:
      tags:
        - Tenants
        - Users
      summary: Update a specific user within a tenant
      responses:
        '200':
          description: User updated
    delete:
      tags:
        - Tenants
        - Users
      summary: Delete a specific user within a tenant
      responses:
        '204':
          description: User deleted
  /tenants/{id}/groups/{group_id}:
    get:
      tags:
        - Tenants
        - Groups
      summary: Get a specific group within a tenant
      responses:
        '200':
          description: A group object
    put:
      tags:
        - Tenants
        - Groups
      summary: Update a specific group within a tenant
      responses:
        '200':
          description: Group updated
    delete:
      tags:
        - Tenants
        - Groups
      summary: Delete a specific group within a tenant
      responses:
        '204':
          description: Group deleted
  /tenants/{id}/vaults/{vault_id}:
    get:
      tags:
        - Tenants
        - Vaults
      summary: Get a specific vault within a tenant
      responses:
        '200':
          description: A vault object
    put:
      tags:
        - Tenants
        - Vaults
      summary: Update a specific vault within a tenant
      responses:
        '200':
          description: Vault updated
    delete:
      tags:
        - Tenants
        - Vaults
      summary: Delete a specific vault within a tenant
      responses:
        '204':
          description: Vault deleted
  /tenants/{id}/secrets/{secret_id}:
    get:
      tags:
        - Tenants
        - Secrets
      summary: Get a specific secret within a tenant
      responses:
        '200':
          description: A secret object
    put:
      tags:
        - Tenants
        - Secrets
      summary: Update a specific secret within a tenant
      responses:
        '200':
          description: Secret updated
    delete:
      tags:
        - Tenants
        - Secrets
      summary: Delete a specific secret within a tenant
      responses:
        '204':
          description: Secret deleted
 
  /groups:
    get:
      tags:
        - groups
      summary: Get all groups
      responses:
        '200':
          description: A list of groups
          schema:
            type: array
            items:
              $ref: '#/definitions/Group'
    post:
      tags:
        - groups
      summary: Create a new group
      parameters:
        - in: body
          name: group
          schema:
            $ref: '#/definitions/Group'
      responses:
        '201':
          description: Group created
  /groups/{id}:
    get:
      tags:
        - groups
      summary: Get a group by ID
      parameters:
        - in: path
          name: id
          required: true
          type: string
      responses:
        '200':
          description: A single group
          schema:
            $ref: '#/definitions/Group'
    put:
      tags:
        - groups
      summary: Update a group by ID
      parameters:
        - in: path
          name: id
          required: true
          type: string
        - in: body
          name: group
          schema:
            $ref: '#/definitions/Group'
      responses:
        '200':
          description: Group updated
    delete:
      tags:
        - groups
      summary: Delete a group by ID
      parameters:
        - in: path
          name: id
          required: true
          type: string
      responses:
        '204':
          description: Group deleted
  
  /roles:
    get:
      tags:
        - roles
      summary: Get all roles
      responses:
        '200':
          description: A list of roles
          schema:
            type: array
            items:
              $ref: '#/definitions/Role'
    post:
      tags:
        - roles
      summary: Create a new role
      parameters:
        - in: body
          name: role
          schema:
            $ref: '#/definitions/Role'
      responses:
        '201':
          description: Role created
  /roles/{id}:
    get:
      tags:
        - roles
      summary: Get a role by ID
      parameters:
        - in: path
          name: id
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: A single role
          schema:
            $ref: '#/definitions/Role'
  
  /permissions:
    get:
      tags:
        - permissions
      summary: Get all permissions
      responses:
        '200':
          description: A list of permissions
          schema:
            type: array
            items:
              $ref: '#/definitions/Permission'
    post:
      tags:
        - permissions
      summary: Create a new permission
      parameters:
        - in: body
          name: permission
          schema:
            $ref: '#/definitions/Permission'
      responses:
        '201':
          description: Permission created
  /permissions/{id}:
    get:
      tags:
        - permissions
      summary: Get a permission by ID
      parameters:
        - in: path
          name: id
          required: true
          type: string
      responses:
        '200':
          description: A single permission
          schema:
            $ref: '#/definitions/Permission'
    put:
      tags:
        - permissions
      summary: Update a permission by ID
      parameters:
        - in: path
          name: id
          required: true
          type: string
        - in: body
          name: permission
          schema:
            $ref: '#/definitions/Permission'
      responses:
        '200':
          description: Permission updated
    delete:
      tags:
        - permissions
      summary: Delete a permission by ID
      parameters:
        - in: path
          name: id
          required: true
          type: string
      responses:
        '204':
          description: Permission deleted
  
  /secrets:
    get:
      tags:
        - secrets
      summary: Get all secrets
      responses:
        '200':
          description: A list of secrets
          schema:
            type: array
            items:
              $ref: '#/definitions/Secret'
    post:
      tags:
        - secrets
      summary: Create a new secret
      parameters:
        - in: body
          name: secret
          schema:
            $ref: '#/definitions/Secret'
      responses:
        '201':
          description: Secret created
  /secrets/{id}:
    get:
      tags:
        - secrets
      summary: Get a secret by ID
      parameters:
        - in: path
          name: id
          required: true
          type: string
      responses:
        '200':
          description: A single secret
          schema:
            $ref: '#/definitions/Secret'
    put:
      tags:
        - secrets
      summary: Update a secret by ID
      parameters:
        - in: path
          name: id
          required: true
          type: string
        - in: body
          name: secret
          schema:
            $ref: '#/definitions/Secret'
      responses:
        '200':
          description: Secret updated
    delete:
      tags:
        - secrets
      summary: Delete a secret by ID
      parameters:
        - in: path
          name: id
          required: true
          type: string
      responses:
        '204':
          description: Secret deleted
  /vaults:
    get:
      tags:
        - vaults
      summary: Get all vaults
      responses:
        '200':
          description: A list of vaults
          schema:
            type: array
            items:
              $ref: '#/definitions/Vault'
    post:
      tags:
        - vaults
      summary: Create a new vault
      parameters:
        - in: body
          name: vault
          schema:
            $ref: '#/definitions/Vault'
      responses:
        '201':
          description: Vault created
  /vaults/{id}:
    get:
      tags:
        - vaults
      summary: Get a vault by ID
      parameters:
        - in: path
          name: id
          required: true
          type: string
      responses:
        '200':
          description: A single vault
          schema:
            $ref: '#/definitions/Vault'
    put:
      tags:
        - vaults
      summary: Update a vault by ID
      parameters:
        - in: path
          name: id
          required: true
          type: string
        - in: body
          name: vault
          schema:
            $ref: '#/definitions/Vault'
      responses:
        '200':
          description: Vault updated
    delete:
      tags:
        - vaults
      summary: Delete a vault by ID
      parameters:
        - in: path
          name: id
          required: true
          type: string
      responses:
        '204':
          description: Vault deleted
definitions:
  User:
    type: object
    properties:
      id:
        type: string
      username:
        type: string
      email:
        type: string
      password:
        type: string
      tenantID:
        type: string
      isActive:
        type: boolean
      isAdmin:
        type: boolean
      activationLink:
        type: string
      isSSOActive:
        type: boolean
  Tenant:
    type: object
    properties:
      id:
        type: string
      region:
        type: string
      users:
        type: array
        items:
          $ref: '#/definitions/User'
      groups:
        type: array
        items:
          $ref: '#/definitions/Group'
      ownerId:
        type: string
  Group:
    type: object
    properties:
      id:
        type: string
      users:
        type: array
        items:
          $ref: '#/definitions/User'
  Role:
    type: object
    properties:
      RoleID:
        type: integer
        format: int32
      RoleName:
        type: string
  Permission:
    type: object
    properties:
      UserID:
        type: string
      GroupID:
        type: string
      RoleID:
        type: string
      VaultID:
        type: string
      Permission:
        type: string
  Secret:
    type: object
    properties:
      VaultID:
        type: string
        format: uuid
      Type:
        type: string
      Value:
        type: string
      SecretOwnerID:
        type: string
        format: uuid
  Vault:
    type: object
    properties:
      TenantID:
        type: string
        format: uuid
      Secrets:
        type: array
        items:
          $ref: '#/definitions/Secret'
      VaultOwnerID:
        type: string
        format: uuid